In [41]:
def testfunc(*args):
    for item in args:
        print(item)
        
    return args
    

In [42]:
testfunc(1,2,3)

1
2
3


(1, 2, 3)

In [59]:
a = testfunc(1, 2, 3,4,5,6,6,7)

1
2
3
4
5
6
6
7


In [60]:
a1, a2, a3 = a

ValueError: too many values to unpack (expected 3)

In [56]:
a1

1

In [57]:
a2

2

In [58]:
a3

3

True

In [23]:
import numpy as np

r=np.empty((2, 1), dtype=bool)

In [25]:
r[0]=False

In [27]:
a = {'r': np.empty((10 * 2, 1), dtype=bool)}

In [28]:
a

{'r': array([[ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True]])}

In [29]:
m=np.empty((10 * 2, 2))

In [30]:
m

array([[6.94332147e-310, 2.01949530e-316],
       [1.52669844e-307, 3.32653169e-111],
       [5.39199055e+067, 8.18974939e-308],
       [3.22925540e-310, 1.95719566e-293],
       [9.97959338e-110, 3.22931810e-310],
       [7.64529557e-296, 8.18974939e-308],
       [1.69364294e-307, 1.63402812e+069],
       [8.18974939e-308, 3.22925540e-310],
       [1.95719566e-293, 9.97959338e-110],
       [9.47780250e+170, 3.35924500e+257],
       [7.02317851e-297, 7.31093862e-314],
       [6.09964693e+149, 8.57621892e-259],
       [3.63521590e+228, 1.33360298e+241],
       [1.16497569e-310, 9.63197468e-196],
       [5.18728502e-313, 1.47106934e-307],
       [1.49091495e-310, 1.40771468e-147],
       [1.15549302e-313, 1.03539814e-308],
       [1.33360293e+241, 5.67421675e-311],
       [5.54667824e-032, 3.70188797e-313],
       [2.14793507e-308, 1.33360297e+241]])

In [31]:
np.zeros((10,1), dtype=bool)

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [32]:
np.ones((10,1),dtype=bool)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [33]:
b=3
e=5

In [34]:
m=np.ones((10,1),dtype=bool)

In [35]:
m[b:e]

array([[ True],
       [ True]])

In [36]:
a={'r':np.ones((10,1), dtype=bool)}

In [38]:
for key in a.keys():
    av=a[key]
    print(av)
    

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


In [40]:
av[::-1]

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])