In [1]:
class bla1():
    def process(self):
        print(1)

class bla2():
    def process(self):
        print(2)
        
    

In [2]:
b1=bla1()
b2=bla2()

In [4]:
[x.process() for x in [b1, b2]]

1
2


[None, None]

In [5]:
import numpy as np

In [19]:
m=np.zeros((12,6), dtype='float')

In [23]:
m[9:12,:]=np.ones((3,6))

In [38]:
def pearsonr_flex(x,y, axis=1):
    # stats.pearsonr adapted for
    # x and y are (N,2) arrays
    n = x.shape[axis]
    mx = x.mean(axis, keepdims=True)
    my = y.mean(axis, keepdims=True)
    xm, ym = x-mx, y-my
    r_num = np.add.reduce(xm * ym, axis)
    r_den = np.sqrt(stats.ss(xm, axis) * stats.ss(ym, axis))
    r = r_num / r_den
    r = np.clip(r, -1.0, 1.0)
    return r

In [44]:
m1=np.random.rand(12,6)
m2=np.random.rand(12,6)
m2

array([[0.34679116, 0.8936184 , 0.84640383, 0.09672329, 0.43251804,
        0.51619471],
       [0.18754777, 0.52229548, 0.92175016, 0.02095587, 0.8182598 ,
        0.49118933],
       [0.67151649, 0.23646395, 0.75000403, 0.39800906, 0.06411516,
        0.62116773],
       [0.69453462, 0.24874361, 0.83726068, 0.70411701, 0.0785189 ,
        0.8019915 ],
       [0.13241591, 0.23255292, 0.99332652, 0.43328813, 0.26181873,
        0.30056802],
       [0.0025687 , 0.19204425, 0.56276091, 0.42345499, 0.11293742,
        0.12124421],
       [0.00837315, 0.55683884, 0.44247945, 0.66387984, 0.07820041,
        0.90729163],
       [0.97537398, 0.52714851, 0.19228746, 0.12836512, 0.13427352,
        0.43708218],
       [0.90797885, 0.15306008, 0.56791497, 0.74432698, 0.46437708,
        0.14850836],
       [0.72991986, 0.04035219, 0.808378  , 0.99626955, 0.53736179,
        0.0240834 ],
       [0.85558998, 0.152231  , 0.39388512, 0.67252002, 0.43231007,
        0.80764987],
       [0.25030305, 0

In [45]:
m1*m2

array([[0.34254024, 0.84984648, 0.32687773, 0.06822776, 0.03927279,
        0.27463369],
       [0.0472539 , 0.50734605, 0.66606218, 0.01173599, 0.58975049,
        0.4779471 ],
       [0.10490915, 0.16975547, 0.16705579, 0.0555157 , 0.01853435,
        0.36255483],
       [0.60860351, 0.24542685, 0.39720532, 0.07315751, 0.01205286,
        0.21702991],
       [0.01960559, 0.1035649 , 0.49364328, 0.30210355, 0.06510588,
        0.10023988],
       [0.0020212 , 0.12268498, 0.47226198, 0.05827255, 0.08924831,
        0.01381072],
       [0.00806752, 0.51659846, 0.21736313, 0.14900544, 0.02869379,
        0.64405838],
       [0.52907153, 0.42725988, 0.15757929, 0.12757619, 0.06046576,
        0.04777872],
       [0.05562927, 0.1337378 , 0.30700207, 0.72677066, 0.27178968,
        0.02663176],
       [0.06438744, 0.0294756 , 0.46825763, 0.93105177, 0.05662301,
        0.01567763],
       [0.26119748, 0.02393536, 0.23148381, 0.51918624, 0.07006942,
        0.43576523],
       [0.12536751, 0

In [50]:
stats.pearsonr

<module 'scipy.stats' from '/home/johan/.conda/envs/rt/lib/python3.6/site-packages/scipy/stats/__init__.py'>

In [49]:
pearsonr_flex(m1, m2, axis=1)

AttributeError: module 'scipy.stats' has no attribute 'ss'

In [25]:
buff_i=90
trsamples=100


In [26]:
trsamples-buff_i

10

In [51]:
from scipy.spatial import distance

In [107]:
distance.directed_hausdorff(m2.T+1, m1.T+1)[0]

1.374760575969181

In [111]:
m1=np.random.random((12,6))
m2=np.random.random((12,6))

In [129]:
m1[:,0] += 3

In [130]:
m1

array([[3.07046918, 2.52574641, 1.21890316, 3.68472698, 0.27925085,
        0.74028423],
       [3.7979424 , 2.14108966, 1.21344201, 3.9541556 , 0.41675068,
        0.81955421],
       [3.56575678, 2.07527314, 1.87997751, 3.98967584, 0.17754381,
        0.98609447],
       [3.55779724, 2.23773213, 1.06357191, 3.12375097, 0.92748448,
        0.58527061],
       [3.84761418, 2.58400163, 1.45113814, 3.33793968, 0.53850356,
        0.23790685],
       [3.05693586, 2.42050751, 1.03665665, 3.47434232, 0.73360477,
        0.68649821],
       [3.5358412 , 2.06870919, 1.81465216, 3.12838008, 0.02167522,
        0.19561614],
       [3.01999488, 2.38707276, 1.43936687, 3.19660668, 0.10285655,
        0.61309821],
       [3.96833398, 2.01472228, 1.92295594, 3.7982986 , 0.01979842,
        0.66996936],
       [3.51999792, 2.08296208, 1.95338834, 3.72629593, 0.05400033,
        0.58114487],
       [3.54590806, 2.64896609, 1.84786083, 3.279024  , 0.76142043,
        0.22176657],
       [3.3533148 , 2

In [131]:
distance.directed_hausdorff(m1.T, m2.T)[0]

9.949301939529038

In [138]:
distance.euclidean(m1.flatten(), m2.flatten())

16.512126604863113

In [142]:
np.correlate(m1.flatten(), m2.flatten())[0]

74.55677369836181

In [143]:
from scipy.stats.stats import pearsonr

In [151]:
pearsonr(m1.flatten(), m2.flatten()+10)[0]

0.11661584271350495

In [159]:
m1 /= 100

In [161]:
m1 += m2

In [164]:
m1=np.ones((1,2))

In [166]:
m2=np.random.rand(1,2)

In [167]:
m1

array([[1., 1.]])

In [170]:
l=[1,2,3,4]


In [168]:
m2

array([[0.63587545, 0.50559273]])

In [169]:
m1 + m2

array([[1.63587545, 1.50559273]])

In [179]:
l

[1, 2, 3, 4]

In [181]:
any([i>0 for i in l])

True

In [178]:
pearsonr?

Signature: pearsonr(x, y)
Docstring:
Calculate a Pearson correlation coefficient and the p-value for testing
non-correlation.

The Pearson correlation coefficient measures the linear relationship
between two datasets. Strictly speaking, Pearson's correlation requires
that each dataset be normally distributed, and not necessarily zero-mean.
Like other correlation coefficients, this one varies between -1 and +1
with 0 implying no correlation. Correlations of -1 or +1 imply an exact
linear relationship. Positive correlations imply that as x increases, so
does y. Negative correlations imply that as x increases, y decreases.

The p-value roughly indicates the probability of an uncorrelated system
producing datasets that have a Pearson correlation at least as extreme
as the one computed from these datasets. The p-values are not entirely
reliable but are probably reasonable for datasets larger than 500 or so.

Parameters
----------
x : (N,) array_like
    Input
y : (N,) array_like
    Input



In [152]:
l=[1,2,3]

In [155]:
l[l.index(2)]

2

In [156]:
l.index(max(l))

2

In [1]:
corrs = [x for x in []]

In [5]:
any([corr == 1 for corr in corrs])

False

In [6]:
l=[1,2,3,4,5]

In [15]:
a, b = zip(*[(N, m) for N, m in enumerate(l)])

In [16]:
a

(0, 1, 2, 3, 4)

In [17]:
b

(1, 2, 3, 4, 5)

In [18]:
enumerate?

Init signature: enumerate(self, /, *args, **kwargs)
Docstring:     
enumerate(iterable[, start]) -> iterator for index, value of iterable

Return an enumerate object.  iterable must be another object that supports
iteration.  The enumerate object yields pairs containing a count (from
start, which defaults to zero) and a value yielded by the iterable argument.
enumerate is useful for obtaining an indexed list:
    (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
Type:           type


In [25]:
l = list(zip([1,2,3,4],[7,8,9,6]))

In [38]:
[(i, lk) for i, (li, lk) in enumerate(l) if lk > 8 and li > 1]

[(2, 9)]

In [54]:
[*map(lambda x: x+1, [1,2,3])]

[2, 3, 4]

In [49]:
f = lambda x: x+1

In [52]:
map(f, (1,2,3))

In [57]:
import numpy as np

In [58]:
m1=np.random.rand(3,2)

In [59]:
m2=np.random.rand(6,2)

In [60]:
m1

array([[0.20826267, 0.75948022],
       [0.67226476, 0.8892357 ],
       [0.24860621, 0.67154785]])

In [62]:
m2

array([[0.01798454, 0.41516767],
       [0.21631623, 0.58797723],
       [0.59597233, 0.42813006],
       [0.26683747, 0.1955528 ],
       [0.9328641 , 0.42963999],
       [0.03252157, 0.68713395]])

In [64]:
np.concatenate((m1, m2))

array([[0.20826267, 0.75948022],
       [0.67226476, 0.8892357 ],
       [0.24860621, 0.67154785],
       [0.01798454, 0.41516767],
       [0.21631623, 0.58797723],
       [0.59597233, 0.42813006],
       [0.26683747, 0.1955528 ],
       [0.9328641 , 0.42963999],
       [0.03252157, 0.68713395]])

In [73]:
m=np.random.rand(3,3)

In [74]:
m[:,:]=0

In [75]:
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
l1=[1,2,3];l2=[3,4,5];l3=[4,5,6]

In [124]:

list(zip(*[*filter(lambda x: x[0]>1, zip(l1, l2, l3))]))

[(2, 3), (4, 5), (5, 6)]

In [116]:
list(zip(*iter([l1, l2, l3])))

[(1, 3, 4), (2, 4, 5), (3, 5, 6)]

AttributeError: module 'itertools' has no attribute 'itertools'